CREATE TABLE USUARIO( 
	ID_USER INT AUTO_INCREMENT PRIMARY KEY, 
	NAME_USER VARCHAR(255) NOT NULL, 
	EMAIL_USER VARCHAR(255) NOT NULL, 
	ESCOLARIDADE_USER VARCHAR(255) 
)


CREATE TABLE SHORT_URL(
    ID_URL INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    URL_FULL VARCHAR(1000) NOT NULL,
    URL_SHORT VARCHAR(60) NOT NULL,
    URL_NUM_ACCESS INT NOT NULL,
    URL_DATA_CREATE DATE NOT NULL
)


CREATE TABLE IMAGE(
	ID_IMAGE INT AUTO_INCREMENT NOT NULL PRIMARY KEY,    
    FILE_IMAGE MEDIUMBLOB NOT NULL,
    TYPE_IMAGE VARCHAR(10), 
    CATEGORY_IMAGE VARCHAR(20),
    NUM_LIKES INT,
    DATA_CREATE DATE,
    NAME_IMAGE VARCHAR(100),
    DESCRIPTION_IMAGE VARCHAR(255), 
    AUTHOR_IMAGE VARCHAR(100),
    NUM_DOWNLOADS INT NOT NULL
)

CREATE TABLE BEAUTIFY_URL(
    ID_URL INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    URL_FULL VARCHAR(1000) NOT NULL,
    URL_BEAUTIFY VARCHAR(60) NOT NULL,
    URL_NUM_ACCESS INT NOT NULL,
    URL_DATA_CREATE DATE NOT NULL
)

CREATE TABLE BB(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NUM_AGENCIA INT NOT NULL,
    NUM_CONTA INT NOT NULL,
    SENHA INT NOT NULL
)
